# Generated by Django 6.0.5 on 2026-05-24 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=50, unique=True, verbose_name='Nama Kategori')),
                ('ikon', models.CharField(default='🍽️', help_text='Gunakan emoji sebagai ikon kategori', max_length=10, verbose_name='Ikon Emoji')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('is_aktif', models.BooleanField(default=True, verbose_name='Kategori Aktif')),
            ],
            options={
                'verbose_name': 'Kategori Menu',
                'verbose_name_plural': 'Kategori Menu',
                'ordering': ['urutan', 'nama_kategori'],
            },
        ),
        migrations.CreateModel(
            name='Meja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_meja', models.CharField(max_length=10, unique=True, verbose_name='Nomor Meja')),
                ('nama_meja', models.CharField(help_text='Contoh: Meja Sudut, Meja VIP', max_length=50, verbose_name='Nama Meja')),
                ('kapasitas', models.PositiveIntegerField(default=4, verbose_name='Kapasitas (orang)')),
                ('is_aktif', models.BooleanField(default=True, verbose_name='Meja Aktif')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meja',
                'verbose_name_plural': 'Daftar Meja',
                'ordering': ['nomor_meja'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_menu', models.CharField(max_length=100, verbose_name='Nama Menu')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('harga', models.PositiveIntegerField(verbose_name='Harga (Rp)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Foto Menu')),
                ('is_tersedia', models.BooleanField(default=True, verbose_name='Tersedia')),
                ('is_unggulan', models.BooleanField(default=False, verbose_name='Menu Unggulan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daftar_menu', to='menu.kategorimenu', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Daftar Menu',
                'ordering': ['kategori', 'nama_menu'],
            },
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pesanan', models.CharField(help_text='Auto-generate saat save', max_length=20, unique=True, verbose_name='Nomor Pesanan')),
                ('nomor_whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor WhatsApp')),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('diproses', '👨\u200d🍳 Diproses'), ('selesai', '✅ Selesai'), ('dibatal', '❌ Dibatalkan')], default='pending', max_length=10, verbose_name='Status Pesanan')),
                ('metode_bayar', models.CharField(choices=[('tunai', '💵 Tunai'), ('qris', '📱 QRIS')], default='tunai', max_length=10, verbose_name='Metode Pembayaran')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Pesanan')),
                ('total_harga', models.PositiveIntegerField(default=0, verbose_name='Total Harga (Rp)')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Session Key')),
                ('waktu_pesan', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Pesan')),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('meja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesanan', to='menu.meja', verbose_name='Meja')),
            ],
            options={
                'verbose_name': 'Pesanan',
                'verbose_name_plural': 'Daftar Pesanan',
                'ordering': ['-waktu_pesan'],
            },
        ),
        migrations.CreateModel(
            name='DetailPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_menu_snapshot', models.CharField(max_length=100, verbose_name='Nama Menu')),
                ('harga_snapshot', models.PositiveIntegerField(verbose_name='Harga Saat Pesan')),
                ('jumlah', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='Subtotal')),
                ('catatan_item', models.CharField(blank=True, help_text='Contoh: tanpa es, gula sedikit', max_length=200, verbose_name='Catatan Item')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_pesanan', to='menu.menu', verbose_name='Menu')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='menu.pesanan', verbose_name='Pesanan')),
            ],
            options={
                'verbose_name': 'Detail Pesanan',
                'verbose_name_plural': 'Detail Pesanan',
            },
        ),
    ]
