# Generated by Django 6.0.5 on 2026-06-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kafe', models.CharField(default='E-Order Café', max_length=100, verbose_name='Nama Kafe')),
                ('alamat_kafe', models.TextField(blank=True, verbose_name='Alamat Kafe')),
                ('telp_kafe', models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon')),
                ('footer_struk', models.CharField(default='Terima kasih sudah berkunjung!', max_length=200, verbose_name='Footer Struk')),
                ('gambar_qris', models.ImageField(blank=True, null=True, upload_to='pengaturan/', verbose_name='Gambar QRIS')),
                ('wifi_aktif', models.BooleanField(default=False, verbose_name='Aktifkan Pembatasan WiFi')),
                ('wifi_ip_range', models.TextField(blank=True, help_text='Satu IP atau range per baris.\nContoh:\n192.168.1.0/24\n192.168.1.100\n10.0.0.0/8', verbose_name='Range IP yang Diizinkan')),
                ('pesan_wifi', models.CharField(default='Anda harus terhubung ke WiFi kafe untuk memesan.', max_length=200, verbose_name='Pesan Error WiFi')),
                ('durasi_session', models.PositiveIntegerField(default=10, verbose_name='Durasi Session (menit)')),
                ('jam_buka', models.TimeField(default='08:00', verbose_name='Jam Buka')),
                ('jam_tutup', models.TimeField(default='22:00', verbose_name='Jam Tutup')),
                ('cek_jam_operasional', models.BooleanField(default=False, verbose_name='Aktifkan Cek Jam Operasional')),
                ('mode_maintenance', models.BooleanField(default=False, verbose_name='Mode Maintenance')),
                ('pesan_maintenance', models.CharField(default='Sistem sedang dalam perbaikan.', max_length=200, verbose_name='Pesan Maintenance')),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan',
                'verbose_name_plural': 'Pengaturan',
            },
        ),
    ]
