# Generated by Django 6.0.5 on 2026-06-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_pengaturan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaturan',
            name='durasi_session',
            field=models.PositiveIntegerField(default=1, verbose_name='Durasi Session (menit)'),
        ),
    ]
