# Generated by Django 6.0.5 on 2026-06-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_pengaturan_durasi_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturan',
            name='wifi_password',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Password WiFi'),
        ),
    ]
