# Generated by Django 6.0.5 on 2026-06-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_pengaturan_wifi_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturan',
            name='notif_loop',
            field=models.BooleanField(default=True, verbose_name='Loop saat ada pesanan pending'),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='notif_suara_pilihan',
            field=models.CharField(choices=[('1', 'Suara 1'), ('2', 'Suara 2'), ('3', 'Suara 3')], default='1', max_length=10, verbose_name='Pilihan Suara'),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='notif_volume',
            field=models.FloatField(default=0.8, verbose_name='Volume (0.0 - 1.0)'),
        ),
    ]
