# Generated by Django 6.0.5 on 2026-06-15 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_pengaturan_notif_loop_pengaturan_notif_suara_pilihan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaturan',
            name='mode_maintenance',
        ),
        migrations.RemoveField(
            model_name='pengaturan',
            name='pesan_maintenance',
        ),
    ]
